build:
  system_packages:
    - "ffmpeg"
    - "libtesseract-dev"
    - "tesseract-ocr"
    - "libssl-dev"
    - "cmake"
  python_packages:
    - "opencv_python==4.8.0.74"
    - "numpy==1.23.5"
    - "python_speech_features==0.6"
    - "resampy==0.4.2"
    - "scipy==1.10.1"
    - "tensorflow==2.13.0"
    - "torch==2.0.1"
    - "torchvision==0.15.2"
    - "gdown==4.7.1"