build:
  system_packages:
    - "ffmpeg"
    - "libtesseract-dev"
    - "tesseract-ocr"
    - "libssl-dev"
    - "cmake"
  python_packages:
    - "opencv-python==4.10.0.84"
    - "numpy==1.26.4"
    - "python_speech_features==0.6"
    - "resampy==0.4.3"
    - "scipy==1.14.1"
    - "tensorflow==2.17.0"
    - "torch==2.4.1"
    - "torchvision==0.19.1"
    - "gdown==4.6.0"
